spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://product-db:5432/product
    username: product
    password: product123
    driver-class-name: org.postgresql.Driver

  eureka:
    client:
      enabled: false